# Create a program that will play the “cows and bulls” game with the user. The game works like this:
#
# Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. For every digit that the user guessed
# correctly in the correct place, they have a “cow”. For every digit the user guessed correctly in the wrong place is a
# “bull.” Every time the user makes a guess, tell them how many “cows” and “bulls” they have. Once the user guesses the
# correct number, the game is over. Keep track of the number of guesses the user makes throughout teh game and tell the
# user at the end.
#
# Say the number generated by the computer is 1038. An example interaction could look like this:
import random
cow = 0
guessed = 1
number = str(random.randint(1000, 9999))

def calculate(number_guessed):
    cows = 0
    bulls = 0
    for i in range(0, 4):
        if number_guessed[i] == number[i]:
            cows += 1
        else:
            bulls += 1
    return cows, bulls

if __name__ == "__main__":
    while cow < 4:
        user_guessed = input("Please enter a four digit number: ")
        cow, bull = calculate(user_guessed)
        print(f"Cows {cow}")
        print(f"Bulls {bull}")
        if cow == 4:
            print(f"Congratulation!! you guessed {number} in {guessed} guesses")
        else:
            guessed += 1